"""Repeated physical contact proves an end without requiring the opposite end."""

import math
from collections import Counter


def _visible(obs):
    counts = Counter(t.stone for t in obs.board)
    return {t.stone: t for t in obs.board if t.stone is not None and counts[t.stone] == 1}


def _touch(a, b):
    x, y, w, h = a.box
    u, v, p, q = b.box
    overlap_x = min(x + w, u + p) - max(x, u)
    overlap_y = min(y + h, v + q) - max(y, v)
    short = min(w, h, p, q)
    return (
        math.hypot(max(0, -overlap_x), max(0, -overlap_y)) < short * 0.25
        and max(overlap_x, overlap_y) > short * 0.4
        and max(0, overlap_x) * max(0, overlap_y) < min(w * h, p * q) * 0.1
    )


def _stable(readings):
    tail = readings[-3:]
    return (
        len({o.time for o, _, _ in tail}) == 3
        and math.dist(tail[0][1].center, tail[-1][1].center) < 4
        and math.dist(tail[0][2].center, tail[-1][2].center) < 4
        and all(
            0 < b[0].time - a[0].time <= 0.15
            and math.dist(a[1].center, b[1].center) < 4
            and math.dist(a[2].center, b[2].center) < 4
            for a, b in zip(tail, tail[1:])
        )
    )


def _projection(hidden, a, b, old, known):
    """Map a known old neighbour through a directly touching A-B pair."""
    oa, ob = old[a], old[b]
    na, nb = known[a], known[b]
    before = complex(*ob.center) - complex(*oa.center)
    after = complex(*nb.center) - complex(*na.center)
    if min(abs(before), abs(after)) < min(*oa.box[2:], *ob.box[2:]) * 0.5:
        return []
    z = after / before
    scale = abs(z)
    if not 0.5 < scale < 2:
        return []
    if any(
        not all(
            0.85 <= n / (scale * o) <= 1.15 for o, n in zip(sorted(x.box[2:]), sorted(y.box[2:]))
        )
        for x, y in ((oa, na), (ob, nb))
    ):
        return []
    matches = []
    for key, tile in old.items():
        if key in (a, b) or not _touch(tile, oa):
            continue
        predicted = complex(*na.center) + (complex(*tile.center) - complex(*oa.center)) * z
        error = abs(predicted - complex(*hidden.center))
        if error < min(hidden.box[2:]) * 0.6 and all(
            0.85 <= n / (scale * o) <= 1.15
            for o, n in zip(sorted(tile.box[2:]), sorted(hidden.box[2:]))
        ):
            matches.append((key, error))
    return matches


def placement_links(event, prior, observations, stop):
    """Return direct contacts or uniquely projected already-known neighbours.

    This records geometry only; the branch-specific chain decides whether a
    neighbour is an end. No tile value or move is generated by these links.
    """
    known_stones = {e["stone"] for e in prior}
    rows = [o for o in observations if event["time"] <= o.time < stop]
    history = [o for o in observations if event["time"] - 3 <= o.time < event["time"]]
    direct, hidden_tracks = {}, []
    for obs in rows:
        visible = _visible(obs)
        tile = visible.get(event["stone"])
        if tile is None:
            continue
        for key, neighbour in visible.items():
            if key in known_stones and _touch(tile, neighbour):
                direct.setdefault(key, []).append((obs, tile, neighbour))
        for hidden in obs.uncertain_board:
            if not _touch(tile, hidden):
                continue
            matches = [
                track
                for track in hidden_tracks
                if 0 < obs.time - track[-1][0].time <= 0.15
                and math.dist(hidden.center, track[-1][2].center) < 4
            ]
            if len(matches) == 1:
                matches[0].append((obs, tile, hidden))
            elif not matches:
                hidden_tracks.append([(obs, tile, hidden)])
    links = [
        dict(stone=key, method="direct_contact", times=[o.time for o, _, _ in track[-3:]])
        for key, track in direct.items()
        if _stable(track)
    ]
    for track in hidden_tracks:
        if not _stable(track):
            continue
        proofs = []
        for obs, tile, hidden in track:
            visible = _visible(obs)
            for a in known_stones & visible.keys():
                if not _touch(hidden, visible[a]):
                    continue
                for b in (known_stones & visible.keys()) - {a}:
                    if not _touch(visible[a], visible[b]):
                        continue
                    for source in history:
                        old = _visible(source)
                        if a not in old or b not in old or not _touch(old[a], old[b]):
                            continue
                        for key, error in _projection(hidden, a, b, old, visible):
                            if key in known_stones:
                                proofs.append(
                                    dict(
                                        stone=key,
                                        time=obs.time,
                                        source=source.time,
                                        anchors=[a, b],
                                        error=error,
                                    )
                                )
        if (
            len({p["stone"] for p in proofs}) != 1
            or len({p["time"] for p in proofs}) < 2
            or len({p["source"] for p in proofs}) < 2
        ):
            continue
        links.append(
            dict(
                stone=proofs[0]["stone"],
                method="projected_contact",
                times=[o.time for o, _, _ in track],
                projection_times=sorted({p["time"] for p in proofs}),
                source_times=sorted({p["source"] for p in proofs}),
                anchors=proofs[0]["anchors"],
                max_error=max(p["error"] for p in proofs),
            )
        )
    return links


def attach_placement_links(rnd, observations):
    events = rnd["events"]
    for index, event in enumerate(events):
        if not event.get("recovery"):
            continue
        stop = min(
            event["time"] + 1, events[index + 1]["time"] if index + 1 < len(events) else rnd["end"]
        )
        if any(
            link.get("event_time") != event["time"] for link in event.get("placement_links", [])
        ):
            event.pop("placement_links", None)
        links = placement_links(event, events[:index], observations, stop)
        if links:
            for link in links:
                link["event_time"] = event["time"]
            event["placement_links"] = links
